### PR TITLE
fix: remove protocolFee refunds

### PR DESCRIPTION
**Pull request by fedealconada**
fixes https://github.com/sherlock-audit/2023-03-sense-judging/issues/40
fixes https://github.com/sherlock-audit/2023-03-sense-judging/issues/33

### CODE REVIEW

**Review by jparklev — APPROVED** [review]
LGTM (note to other reviewers the comment on discussions w 0x in the commit msg)

**Review by jparklev — COMMENTED** [review]
@fedealconada question about https://github.com/sherlock-audit/2023-03-sense-judging/issues/33:

Should we use `call` instead of `transfer` elsewhere as well? (like in the `_transfer` function)

**Comment by fedealconada** [comment]
> @fedealconada question about [sherlock-audit/2023-03-sense-judging#33](https://github.com/sherlock-audit/2023-03-sense-judging/issues/33):
> 
> Should we use `call` instead of `transfer` elsewhere as well? (like in the `_transfer` function)

yes! pushed :) i don't think we have any other place than that

**Review by IAm0x52 — COMMENTED** [review]
I believe you missed this transfer:

https://github.com/sherlock-audit/2023-03-sense/blob/52049213bdff31138c43a28f061fea493b3d7e14/auto-roller/src/RollerPeriphery.sol#L111

**Review by IAm0x52 — COMMENTED** [review]
Additionally I believe you also missed this refund:

https://github.com/sherlock-audit/2023-03-sense/blob/52049213bdff31138c43a28f061fea493b3d7e14/auto-roller/src/RollerPeriphery.sol#L258-L260

**Comment by fedealconada** [comment]
> I believe you missed this transfer:
> 
> https://github.com/sherlock-audit/2023-03-sense/blob/52049213bdff31138c43a28f061fea493b3d7e14/auto-roller/src/RollerPeriphery.sol#L111

> Additionally I believe you also missed this refund:
> 
> https://github.com/sherlock-audit/2023-03-sense/blob/52049213bdff31138c43a28f061fea493b3d7e14/auto-roller/src/RollerPeriphery.sol#L258-L260

both fixed here: https://github.com/sense-finance/auto-roller/pull/34

**Comment by jparklev** [comment]
@fedealconada looks like sense-v1 is mentioned in this comment as well, do u know what he's referring to? (from https://github.com/sherlock-audit/2023-03-sense-judging/issues/33)
Screen Shot 2023-04-17 at 10 37 21 AM

**Pull request merged**
